home:
  path: /
  controller: App\Controller\DefaultController::indexAction

update:
  path: /admin/update/{id}/{name}
  controller: App\Controller\UpdateController::updateController

addNewObject:
  path: /admin/add/{name}
  controller: App\Controller\NewObjectController::newObjectAction

delete:
  path: /admin/delete/{id}/{name}
  controller: App\Controller\DeleteController::deleteAction

projets:
  path: /projets/{name}/{searchId}
  controller: App\Controller\ProjetsController::projetsAction

adminHome:
  path: /admin/
  controller: App\Controller\Admin\AdminController::indexAction


